### ISSUE TITLE
Item NBT models should be mentioned

### ISSUE THREAD

**Issue by machinesmith42** [i-like-trains72/optifine-resourcepack-conversion#10]

**Comment by i-like-trains72** [comment]
Could you give me a link to Item NBT models? I know I've heard of it on Lambda's OF alternative gist.

**Comment by machinesmith42** [comment]
https://www.curseforge.com/minecraft/mc-mods/itemnbtmodels

**Comment by i-like-trains72** [comment]
I'd mention it but..
> Unfortunately, i do not have the time or technology to develop this in the manner i had planned. It will sit as is for the time being. It is MIT and if someone wants to take over the project, let me know. It will likely not see any updates for quite some time.

I do not know enough Java to fix it before 1.17 drops so we can't do anything about it ATM

**Comment by i-like-trains72** [comment]
I hope to fix it myself but yall know how terrible Optifine is :>
