### ISSUE TITLE
This should be a gist

### ISSUE THREAD

**Issue by machinesmith42** [i-like-trains72/optifine-resourcepack-conversion#2]

**Comment by i-like-trains72** [comment]
I'd make it one but READMEs are less cluttered for this purpose. I will be providing bundled releases that update with each mods' update. If FSB updates, I will make a new minor release and tag it FSB update. Ditto for MCPP and colormatic.

**Comment by machinesmith42** [comment]
do not upload releases from other people's mods please just link

**Comment by i-like-trains72** [comment]
I have permission and this is supposed to be really easy to use.

**Comment by machinesmith42** [comment]
hmm make a download script

**Comment by machinesmith42** [comment]
to make sure updates get linked

**Comment by i-like-trains72** [comment]
A download script is a good idea. I'll get that sorted out in the future though. I could find a way to use the githubs of the mods and download stable releases for them. Not sure how that'd work but I'll figure it out.
