### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by i-like-trains72** [i-like-trains72/optifine-resourcepack-conversion#4]
i have to change the name, shaders makes it seem like actual shaders.
@DragonEggBedrockBreaking 
help mee

**Comment by DragonEggBedrockBreaking** [comment]
Enhanced-Lighting

**Comment by i-like-trains72** [comment]
but this is supposed to do more than that.
its supposed to make custom entity models work, custom item textures, etc. 
granted, that'll come in the future but i dont wanna change it. i was thinking of Optifine 2 but I hate optifine for the most part so I opted not to use it

**Comment by DragonEggBedrockBreaking** [comment]
Sodium-Goes-Brrrr

**Comment by i-like-trains72** [comment]
i actually like that but its too vague for now. will think on this in the future
