### ISSUE TITLE
Credit StitchYYT for SimpleShaders

### ISSUE THREAD

**Issue by ReperakDev** [i-like-trains72/optifine-resourcepack-conversion#5]
[CurseForge](https://www.curseforge.com/members/itsstitchyyt)

[Reddit](https://www.reddit.com/user/StitchYYT/)

Also get permission from them, they've not included a license and therefore you have no permission to redistribute.

**Comment by i-like-trains72** [comment]
I got permission from them in Curseforge DMs a long time ago to redistribute/edit
Will cite the resourcepack though

**Comment by i-like-trains72** [comment]
https://github.com/i-like-trains72/optifine-resourcepack-conversion/commit/af7ef72df8ae142124d56858910faf68ecd4141a

Fixed :)
