### ISSUE TITLE
you spelt resourcepacks wrong

### ISSUE THREAD

**Issue by supsm** [i-like-trains72/optifine-resourcepack-conversion#7]
you spelt "resourcepacks" as "resourepacks" (forgot the c)

**Comment by i-like-trains72** [comment]
where was this

**Comment by i-like-trains72** [comment]
did ctrl f and i cant find the word resourepacks.

**Comment by i-like-trains72** [comment]
mate i can't find a misspelling

**Comment by supsm** [comment]
here it is lol
![image](https://user-images.githubusercontent.com/60897356/118220128-c1093200-b42f-11eb-946a-0435143f3b0c.png)

**Comment by i-like-trains72** [comment]
oopsie

**Comment by i-like-trains72** [comment]
will fix tomorrow or saturday

**Comment by ReperakDev** [comment]
Why is this still open

**Comment by DragonEggBedrockBreaking** [comment]
lmao

**Comment by i-like-trains72** [comment]
shhhhhhhhhhhhhhhhhhhhhhhh
ill fix it

**Comment by ReperakDev** [comment]
you still didnt fix it

**Comment by i-like-trains72** [comment]
fixed

**Comment by supsm** [comment]
lol
